<% application_name = 'virtuous' %>
defaults: &defaults
  adapter: mysql2
  username: root
  password: password
  host: localhost
  encoding: utf8

development:
  database: <%= application_name %>_development
  <<: *defaults

test:
  database: <%= application_name %>_test
  <<: *defaults
